# Sqlg configuration for PostgreSQL
# Docs: https://sqlg.org/docs/3.1.6/
jdbc.url=jdbc:postgresql://192.168.31.112:5432/sqlgmngdb
jdbc.username=sqlg_mng
jdbc.password=sqlg_mng
# Tell sqlg to use the HikariCP connection pool implementation
sqlg.dataSource=org.umlg.sqlg.datasource.HikariSqlgDataSource
